import { useState } from 'react';
import { Form, Link, useActionData, useLoaderData, useNavigation } from 'react-router-dom';
import { EmptyState, Page, PageHeader } from '../components/ui';
import type { CareRoundActionData, CareRoundData, CareRoundMember } from './care-round-data';
import type { CareEventType } from './plants-data';

export function CareRoundRoute() {
  const data = useLoaderData<CareRoundData>(); const action = useActionData<CareRoundActionData>(); const navigation = useNavigation(); const [confirm, setConfirm] = useState(false);
  if (action?.completed) return <Page width="reading"><PageHeader eyebrow="Round complete" title="Care summary" description={`${action.completed.locationName} care round completed.`} /><Summary members={action.completed.summary} /><Link className="btn-primary mt-6 inline-flex" to="/">Continue to Home</Link></Page>;
  const round = data.active;
  if (!round) return <Page width="reading"><PageHeader eyebrow="Routine care" title="Start a care round" description="Choose one location and work through its active plants." />{action && !action.ok && <Message action={action} />}{data.options.length === 0 ? <EmptyState description="Add active plants to a location, or leave them unassigned, before starting a round." title="No plants available" /> : <Form className="card mt-6 grid gap-4 p-5" method="post"><input name="intent" type="hidden" value="start" /><label className="grid gap-1 text-sm font-medium">Location<select className="min-h-11 rounded-lg border border-neutral-300 bg-white px-3" name="locationId">{data.options.map((option) => <option key={option.locationId ?? 'none'} value={option.locationId ?? 'none'}>{option.name} ({option.plantCount})</option>)}</select></label><button className="btn-primary" disabled={navigation.state !== 'idle'} type="submit">Start round</button></Form>}</Page>;
  const current = round.members[round.currentIndex];
  return <Page width="reading"><PageHeader eyebrow={round.locationName} title="Care round" description={`Plant ${Math.min(round.currentIndex + 1, round.members.length)} of ${round.members.length}`} />{action && <Message action={action} />}{current ? <><section className="card mt-6 p-5"><h2 className="text-2xl font-bold">{current.nickname}</h2><p className="mt-1 text-neutral-600">{current.speciesName}</p>{current.available ? <CareForm roundId={round.id} plantId={current.plantId!} /> : <p className="mt-4 text-red-700">This snapshot plant is no longer active or available. Skip it to continue.</p>}</section><Progress roundId={round.id} previous={round.currentIndex > 0} /></> : <section className="card mt-6 p-5 text-center"><h2 className="text-xl font-semibold">Round ready to complete</h2><p className="mt-2 text-neutral-600">You have advanced beyond the final plant.</p></section>}<button className="btn-secondary mt-6" onClick={() => setConfirm(true)} type="button">Complete round</button>{confirm && <CompletionDialog onCancel={() => setConfirm(false)} roundId={round.id} />}</Page>;
}

function CareForm({ roundId, plantId }: { roundId: number; plantId: number }) { const [type, setType] = useState<CareEventType>('watering'); return <Form className="mt-5 grid gap-3 border-t border-neutral-200 pt-5" method="post"><input name="intent" type="hidden" value="record" /><input name="roundId" type="hidden" value={roundId} /><input name="plantId" type="hidden" value={plantId} /><label className="grid gap-1 text-sm font-medium">Care type<select className="min-h-11 rounded-lg border border-neutral-300 bg-white px-3" name="type" onChange={(event) => setType(event.target.value as CareEventType)} value={type}><option value="watering">Watering</option><option value="pruning">Pruning</option><option value="repotting">Repotting</option><option value="pest-treatment">Pest treatment</option><option value="observation">Observation</option></select></label><label className="grid gap-1 text-sm font-medium">Happened at<input className="min-h-11 rounded-lg border border-neutral-300 px-3" defaultValue={localValue(new Date())} max={localValue(new Date())} name="timestamp" required type="datetime-local" /></label><label className="grid gap-1 text-sm font-medium">Notes <span className="font-normal text-neutral-500">(optional)</span><textarea className="min-h-20 rounded-lg border border-neutral-300 p-2" name="notes" /></label>{type === 'watering' && <label className="flex min-h-11 items-center gap-2"><input name="fertilizerIncluded" type="checkbox" /> Fertilizer included</label>}<button className="btn-primary" type="submit">Record care</button></Form>; }
function Progress({ roundId, previous }: { roundId: number; previous: boolean }) { return <div className="mt-4 flex justify-between gap-3">{previous ? <Form method="post"><input name="intent" type="hidden" value="previous" /><input name="roundId" type="hidden" value={roundId} /><button className="btn-secondary" type="submit">Previous plant</button></Form> : <span />}<Form method="post"><input name="intent" type="hidden" value="skip" /><input name="roundId" type="hidden" value={roundId} /><button className="btn-secondary" type="submit">Skip / next plant</button></Form></div>; }
function CompletionDialog({ onCancel, roundId }: { onCancel: () => void; roundId: number }) { return <div aria-modal="true" className="fixed inset-0 z-30 grid place-items-center bg-neutral-950/40 p-4" role="dialog"><section className="w-full max-w-md rounded-xl bg-white p-6"><h2 className="text-xl font-semibold">Complete this care round?</h2><p className="mt-3 text-neutral-600">Recorded care will remain in plant history. Remaining plants will receive no invented events.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={onCancel} type="button">Cancel</button><Form method="post"><input name="intent" type="hidden" value="complete" /><input name="roundId" type="hidden" value={roundId} /><button className="btn-primary" type="submit">Complete round</button></Form></div></section></div>; }
function Summary({ members }: { members: CareRoundMember[] }) { return members.length === 0 ? <p className="mt-6 text-neutral-600">No care events were recorded during this round.</p> : <ul className="mt-6 grid gap-3">{members.map((member) => <li className="card p-4" key={`${member.position}-${member.nickname}`}><p className="font-semibold">{member.nickname}</p><p className="text-sm text-neutral-600">{member.speciesName}</p></li>)}</ul>; }
function Message({ action }: { action: CareRoundActionData }) { return <p className={`mt-4 text-sm ${action.ok ? 'text-green-700' : 'text-red-700'}`} role={action.ok ? 'status' : 'alert'}>{action.message}</p>; }
function localValue(date: Date): string { const offset = date.getTimezoneOffset() * 60_000; return new Date(date.valueOf() - offset).toISOString().slice(0, 16); }
