export enum WateringStrategy {
  KEEP_EVENLY_MOIST = 'KEEP_EVENLY_MOIST',
  WATER_WHEN_TOP_SOIL_DRY = 'WATER_WHEN_TOP_SOIL_DRY',
  LET_MOSTLY_DRY_OUT = 'LET_MOSTLY_DRY_OUT',
  LET_FULLY_DRY_OUT = 'LET_FULLY_DRY_OUT',
}
