import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateLocations1786453200000 implements MigrationInterface {
  name = 'CreateLocations1786453200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "locations" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" text NOT NULL,
        CONSTRAINT "PK_locations" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_locations_name_present" CHECK (length(rtrim("name")) > 0),
        CONSTRAINT "CHK_locations_name_trailing_whitespace" CHECK ("name" = rtrim("name"))
      )
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX "UQ_locations_name_case_insensitive"
      ON "locations" (LOWER("name"))
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "locations"');
  }
}
