import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCareEvents1786500000000 implements MigrationInterface {
  name = 'CreateCareEvents1786500000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "care_events" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "plant_id" integer NOT NULL,
        "type" character varying(32) NOT NULL,
        "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL,
        "notes" text,
        "fertilizer_included" boolean,
        CONSTRAINT "PK_care_events" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_care_events_type" CHECK ("type" IN ('watering', 'pruning', 'repotting', 'pest-treatment', 'observation')),
        CONSTRAINT "FK_care_events_plant" FOREIGN KEY ("plant_id") REFERENCES "plants"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(
      'CREATE INDEX "IDX_care_events_plant_timestamp" ON "care_events" ("plant_id", "timestamp")',
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "care_events"');
  }
}
