import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePlantImages1786510000000 implements MigrationInterface {
  name = 'CreatePlantImages1786510000000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "plant_images" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "plant_id" integer NOT NULL, "storage_key" text NOT NULL, "media_type" character varying(16) NOT NULL, "byte_size" integer NOT NULL, "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_plant_images_storage_key" UNIQUE ("storage_key"), CONSTRAINT "PK_plant_images" PRIMARY KEY ("id"), CONSTRAINT "FK_plant_images_plant" FOREIGN KEY ("plant_id") REFERENCES "plants"("id") ON DELETE CASCADE)`);
    await queryRunner.query('CREATE INDEX "IDX_plant_images_plant_added" ON "plant_images" ("plant_id", "added_at", "id")');
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "IDX_plant_images_plant_added"');
    await queryRunner.query('DROP TABLE "plant_images"');
  }
}
