import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePlants1786454626591 implements MigrationInterface {
  name = 'CreatePlants1786454626591';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "plants" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "nickname" text NOT NULL,
        "species_id" integer NOT NULL,
        "acquisition_date" date NOT NULL,
        "notes" text,
        "status" character varying(10) NOT NULL DEFAULT 'active',
        "location_id" integer,
        CONSTRAINT "PK_plants" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_plants_nickname_present" CHECK (length(trim("nickname")) > 0),
        CONSTRAINT "CHK_plants_status" CHECK ("status" IN ('active', 'dead', 'archived')),
        CONSTRAINT "FK_plants_species" FOREIGN KEY ("species_id") REFERENCES "species"("id") ON DELETE RESTRICT,
        CONSTRAINT "FK_plants_location" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL
      )
    `);
    await queryRunner.query(
      'CREATE INDEX "IDX_plants_species_id" ON "plants" ("species_id")',
    );
    await queryRunner.query(
      'CREATE INDEX "IDX_plants_location_id" ON "plants" ("location_id")',
    );
    await queryRunner.query(
      'CREATE INDEX "IDX_plants_status" ON "plants" ("status")',
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "plants"');
  }
}
