import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCareRounds1786520000000 implements MigrationInterface {
  name = 'CreateCareRounds1786520000000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "care_rounds" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "location_id" integer, "location_name" text, "status" character varying(12) NOT NULL DEFAULT 'active', "current_index" integer NOT NULL DEFAULT 0, "started_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_care_rounds_status" CHECK ("status" IN ('active', 'completed')), CONSTRAINT "PK_care_rounds" PRIMARY KEY ("id"))`);
    await queryRunner.query('CREATE UNIQUE INDEX "UQ_care_rounds_one_active" ON "care_rounds" ("status") WHERE "status" = \'active\'');
    await queryRunner.query(`CREATE TABLE "care_round_members" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "round_id" integer NOT NULL, "plant_id" integer, "position" integer NOT NULL, "plant_nickname" text NOT NULL, "species_name" text NOT NULL, CONSTRAINT "PK_care_round_members" PRIMARY KEY ("id"), CONSTRAINT "FK_care_round_members_round" FOREIGN KEY ("round_id") REFERENCES "care_rounds"("id") ON DELETE CASCADE, CONSTRAINT "FK_care_round_members_plant" FOREIGN KEY ("plant_id") REFERENCES "plants"("id") ON DELETE SET NULL)`);
    await queryRunner.query('CREATE UNIQUE INDEX "UQ_care_round_members_position" ON "care_round_members" ("round_id", "position")');
    await queryRunner.query('CREATE UNIQUE INDEX "UQ_care_round_members_plant" ON "care_round_members" ("round_id", "plant_id")');
    await queryRunner.query('ALTER TABLE "care_events" ADD "round_id" integer');
    await queryRunner.query('ALTER TABLE "care_events" ADD CONSTRAINT "FK_care_events_round" FOREIGN KEY ("round_id") REFERENCES "care_rounds"("id") ON DELETE SET NULL');
    await queryRunner.query('CREATE INDEX "IDX_care_events_round_id" ON "care_events" ("round_id")');
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "IDX_care_events_round_id"');
    await queryRunner.query('ALTER TABLE "care_events" DROP CONSTRAINT "FK_care_events_round"');
    await queryRunner.query('ALTER TABLE "care_events" DROP COLUMN "round_id"');
    await queryRunner.query('DROP TABLE "care_round_members"');
    await queryRunner.query('DROP INDEX "UQ_care_rounds_one_active"');
    await queryRunner.query('DROP TABLE "care_rounds"');
  }
}
