export enum CareLogType {
  WATER = 'WATER',
  FERTILIZE = 'FERTILIZE',
  PRUNE = 'PRUNE',
  REPOT = 'REPOT',
  CHECK = 'CHECK',
  MOVE_INSIDE = 'MOVE_INSIDE',
  MOVE_OUTSIDE = 'MOVE_OUTSIDE',
  PEST_TREATMENT = 'PEST_TREATMENT',
}
