ALTER TABLE t_plant
    ADD COLUMN removed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN died BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN inactive_reason TEXT,
    ADD COLUMN inactive_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
